config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :company_types
  root 'companies#index'
end

app/models/company.rb
class Company < ActiveRecord::Base
	include ImageUploader[:image]
  belongs_to :company_type
end

app/models/company_type.rb
class CompanyType < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :description, :image, :views_count, :enquires_count, :connects_count, :is_approved, :company_type_id)
    end
end

app/controllers/company_types_controller.rb
class CompanyTypesController < ApplicationController
  before_action :set_company_type, only: [:show, :edit, :update, :destroy]

  # GET /company_types
  # GET /company_types.json
  def index
    @company_types = CompanyType.all
  end

  # GET /company_types/1
  # GET /company_types/1.json
  def show
  end

  # GET /company_types/new
  def new
    @company_type = CompanyType.new
  end

  # GET /company_types/1/edit
  def edit
  end

  # POST /company_types
  # POST /company_types.json
  def create
    @company_type = CompanyType.new(company_type_params)

    respond_to do |format|
      if @company_type.save
        format.html { redirect_to @company_type, notice: 'Company type was successfully created.' }
        format.json { render :show, status: :created, location: @company_type }
      else
        format.html { render :new }
        format.json { render json: @company_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /company_types/1
  # PATCH/PUT /company_types/1.json
  def update
    respond_to do |format|
      if @company_type.update(company_type_params)
        format.html { redirect_to @company_type, notice: 'Company type was successfully updated.' }
        format.json { render :show, status: :ok, location: @company_type }
      else
        format.html { render :edit }
        format.json { render json: @company_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company_types/1
  # DELETE /company_types/1.json
  def destroy
    @company_type.destroy
    respond_to do |format|
      format.html { redirect_to company_types_url, notice: 'Company type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company_type
      @company_type = CompanyType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_type_params
      params.require(:company_type).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/company_types_helper.rb
module CompanyTypesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @company.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h4>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :views_count, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :views_count, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :enquires_count, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :enquires_count, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :connects_count, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :connects_count, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :is_approved, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :is_approved, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image, class: "col-sm-2 control-label" %>
    <%= f.hidden_field :image, value: f.object.cached_image_data %>
    <div class="col-sm-10">
      <%= f.file_field :image %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/companies/edit.html.erb
<div class="page-header">
  <%= link_to companies_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @company, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing company</h1>
</div>

<%= render 'form' %>

app/views/companies/index.html.erb
<div class="page-header">
  <%= link_to new_company_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Company
  <% end %>
  <h1>Listing companies</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Views count</th>
            <th>Enquires count</th>
            <th>Connects count</th>
            <th>Is approved</th>
            <th>Company type</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @companies) do |company| %>
            <td><%= company.name %></td>
            <td><%= company.description %></td>
            <td><%= company.views_count %></td>
            <td><%= company.enquires_count %></td>
            <td><%= company.connects_count %></td>
            <td><%= company.is_approved %></td>
            <td><%= company.company_type %></td>
            <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/companies/new.html.erb
<div class="page-header">
  <%= link_to companies_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New company</h1>
</div>

<%= render 'form' %>

app/views/companies/show.html.erb
<div class="page-header">
  <%= link_to companies_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_company_path(@company), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show company</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @company.name %></dd>

  <dt>Description:</dt>
  <dd><%= @company.description %></dd>

  <dt>Views count:</dt>
  <dd><%= @company.views_count %></dd>

  <dt>Enquires count:</dt>
  <dd><%= @company.enquires_count %></dd>

  <dt>Connects count:</dt>
  <dd><%= @company.connects_count %></dd>

  <dt>Is approved:</dt>
  <dd><%= @company.is_approved %></dd>

  <dt>Company type:</dt>
  <dd><%= @company.company_type %></dd>

  <dt>Company Logo:</dt>
  <dd><img src="<%= @company.image_url %>"></dd>

</dl>

app/views/company_types/_form.html.erb
<%= form_for(@company_type, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @company_type.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@company_type.errors.count, "error") %> prohibited this company_type from being saved:</h4>

      <ul>
      <% @company_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/company_types/edit.html.erb
<div class="page-header">
  <%= link_to company_types_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @company_type, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing company_type</h1>
</div>

<%= render 'form' %>

app/views/company_types/index.html.erb
<div class="page-header">
  <%= link_to new_company_type_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Company type
  <% end %>
  <h1>Listing company_types</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @company_types) do |company_type| %>
            <td><%= company_type.name %></td>
            <td><%= link_to 'Show', company_type %></td>
        <td><%= link_to 'Edit', edit_company_type_path(company_type) %></td>
        <td><%= link_to 'Destroy', company_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/company_types/new.html.erb
<div class="page-header">
  <%= link_to company_types_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New company_type</h1>
</div>

<%= render 'form' %>

app/views/company_types/show.html.erb
<div class="page-header">
  <%= link_to company_types_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_company_type_path(@company_type), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show company_type</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @company_type.name %></dd>

</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Industry Connect</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "INDUSTRY CONNECT", root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="<%= controller.controller_name == 'home' ? 'active' : 'none' %>"><%= link_to "Home", root_path %></li>
          <li class="<%= controller.controller_name == 'companies' ? 'active' : 'none' %>"><%= link_to "Companies", companies_path %></li>
          <li class="<%= controller.controller_name == 'company_types' ? 'active' : 'none' %>"><%= link_to "Company Types", company_types_path %></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>